---
credentials:
  - username: dzmitry_asetnik
    password: $6$D65ClFWHCAR253gN$BT5BM.M8ylRRRVbn/9u/qsOPPimyZs4PX.r.FyZ5yGgtOmMVdYB/KcmND2Ox7dpl3YVY7/ZCaTUG6teQ/dZVw/
  - username: phillip_haslett
    password: $6$D65ClFWHCAR253gN$BT5BM.M8ylRRRVbn/9u/qsOPPimyZs4PX.r.FyZ5yGgtOmMVdYB/KcmND2Ox7dpl3YVY7/ZCaTUG6teQ/dZVw/
  - username: veronika_hettlinger
    password: $6$D65ClFWHCAR253gN$BT5BM.M8ylRRRVbn/9u/qsOPPimyZs4PX.r.FyZ5yGgtOmMVdYB/KcmND2Ox7dpl3YVY7/ZCaTUG6teQ/dZVw/
  - username: onemoreuser
    password: $6$D65ClFWHCAR253gN$BT5BM.M8ylRRRVbn/9u/qsOPPimyZs4PX.r.FyZ5yGgtOmMVdYB/KcmND2Ox7dpl3YVY7/ZCaTUG6teQ/dZVw/
  - username: oneonemoreuser
    password: $6$D65ClFWHCAR253gN$BT5BM.M8ylRRRVbn/9u/qsOPPimyZs4PX.r.FyZ5yGgtOmMVdYB/KcmND2Ox7dpl3YVY7/ZCaTUG6teQ/dZVw/
