---
- name: epel-release
  yum: name=epel-release state=present
  become: true

- name: installing the latest version of nginx
  yum: name=nginx state=present
  become: true

- name: copy custom page
  copy:
    src: index.html
    dest: /usr/share/nginx/html/
  become: true
  notify: restart nginx
