FROM mysql:latest

VOLUME /home/vagrant/mysql:/var/lib/mysql

ENV  MYSQL_ROOT_PASSWORD={{ mysql.root_password }}
ENV  MYSQL_DATABASE={{ mysql.database }}
ENV  MYSQL_USER={{ mysql.username }}
ENV  MYSQL_PASSWORD={{ mysql.user_password }}