---
- name: create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
  become: true
  with_items:
    - "{{ credentials }}"

- name: create a html directory if it does not exist
  file:
    path: /var/www/{{ item.username }}/html
    state: directory
    owner: "{{ item.username }}"
  become: true
  with_items:
    - "{{ credentials }}"
  notify: check user directory exist

- name: copy custom page
  vars:
    username: "{{ item.username }}"
  template:
    src: templates/index.html.j2
    dest: /var/www/{{ username }}/html/index.html
  tags: create_index.html
  with_items:
    - "{{ credentials }}"
  become: true

- name: recursively change permissions
  file:
    path: /var/www
    mode: 0755
    state: directory
    recurse: yes
  become: true

- name: create a server block files
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  become: true
  with_items:
    - sites-available
    - sites-enabled

- name: copy first part config files
  vars:
    username: "{{ item[0].username }}"
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/sites-available/{{ username }}.conf
    mode: 666
  with_together:
    - "{{ credentials }}"
  become: true

- name: copy second part config files
  vars:
    username: "{{ item[0].username }}"
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/sites-enabled/{{ username }}.conf
    mode: 666
  with_together:
    - "{{ credentials }}"
  become: true

- name: copy nginx.conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: true
  notify: restart nginx

- name: copy hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
  become: true
