---
- name: create mysql directory
  file:
    path: /opt/mysql
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755
  become: true

- name: Create a network
  community.docker.docker_network:
    name: "{{ mysql.network_name }}"
  become: true

- name: create dockerfile
  template:
    src: templates/Dockerfile.j2
    dest: /opt/mysql/Dockerfile
    mode: 644

- name: build an image
  community.docker.docker_image:
    build:
      path: /opt/mysql
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    source: build
  become: true

- name: create container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    network_mode: bridge
    networks: 
      - name: "{{ mysql.network_name }}"
  become: true
