FROM wordpress:latest

ENV WORDPRESS_DB_HOST={{ name_of_sql }}:3306
ENV WORDPRESS_DB_NAME={{ mysql.database }}
ENV WORDPRESS_DB_USER={{ mysql.username }}
ENV WORDPRESS_DB_PASSWORD={{ mysql.user_password }}