---
- name: install docker CentOS
  block: 
    - name: installing necessary docker packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python-docker-py
        state: latest
      become: true

    - name: configuring docker-ce rep
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
      become: true

    - name: install docker
      yum:
        name: docker-ce
        state: latest
      become: true

    - name: add user to docker group
      user:
        name: vagrant
        group: docker
      become: true
    
    - name: start docker
      service:
        name: docker
        state: started
        enabled: true
      become: true
  when: ansible_facts['distribution'] == 'CentOS'

- name: install docker Ubuntu
  block:
    - name: install required dependencies 
      apt: 
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - python3-docker
          - pip
        state: latest 
        update_cache: true 
      become: true

    - name: add docker gpg apt key 
      become: true
      apt_key:
        state: present
        keyserver: 'https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg'
        id: 7EA0A9C3F273FCD8

    - name: add docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
        state: present
      become: true

    - name: update apt and install docker-ce 
      apt: 
        update_cache: true 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
      become: true

    - name: add user to docker group
      user:
        name: vagrant
        group: docker
      become: true
  
    - name: start docker
      service:
        name: docker
        state: started
        enabled: true
      become: true
  when: ansible_facts['distribution'] == 'Ubuntu'